# Generated by Django 3.1.6 on 2021-02-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AddField(
            model_name='poll',
            name='option_eight_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_five_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_four_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_seven_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_six_count',
            field=models.IntegerField(default=0),
        ),
    ]
