# Generated by Django 3.1.6 on 2021-02-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210206_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='option_eight_count',
            new_name='option_4',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_five_count',
            new_name='option_5',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_four_count',
            new_name='option_6',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_one_count',
            new_name='option_7',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_seven_count',
            new_name='option_8',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_six_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two_count',
        ),
        migrations.AddField(
            model_name='poll',
            name='option_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_3',
            field=models.IntegerField(default=0),
        ),
    ]
