# Generated by Django 3.1.6 on 2021-02-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210206_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.IntegerField(default=0)),
                ('option_2', models.IntegerField(default=0)),
                ('option_3', models.IntegerField(default=0)),
                ('option_4', models.IntegerField(default=0)),
                ('option_5', models.IntegerField(default=0)),
                ('option_6', models.IntegerField(default=0)),
                ('option_7', models.IntegerField(default=0)),
                ('option_8', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Poll',
            new_name='BadPoll',
        ),
    ]
